info:
  name: Delete Multiple Roles
  type: http
  seq: 5

http:
  method: DELETE
  url: "{{blogForge}}/api/v1/roles"
  body:
    type: json
    data: |-
      {
        "roles":["adsj", "elder"]
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
