info:
  name: Get My Author Applications
  type: http
  seq: 2

http:
  method: GET
  url: "{{blogForge}}/api/v1/me/author-applications"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
